### ISSUE TITLE
For add this list in awesome need make some things

### ISSUE THREAD

**Issue by Drsheppard01** [akvadrako/awesome-flatpak#2]
1. Add badge
2. Add the license CC in separate file
3. Rename branch into main
4. Remove #Contributing section
5. Remove #License section
6. Add Contributing.md

All guideline https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md
My pull request for add this list in awesome.rs https://github.com/sindresorhus/awesome/pull/2410 for resolve https://github.com/akvadrako/awesome-flatpak/pull/1#discussion_r997811506

Yours sincerely, DrSheppard

**Comment by akvadrako** [comment]
Yes, but I'm not going to do these things.

**Comment by akvadrako** [comment]
FYI I have created a fork of sindresorhus' list and included flatpak in it: https://github.com/0ex/more-awesome.
